# DB Config file

development:
  adapter: CassandraObject
  database: am_chat_dev
  username: root 
  password: root
  host: localhost

test:
  adapter: CassandraObject
  database: am_chat_test
  username: root
  password: root
  host: localhost

production:
  adapter: CassandraObject
  database: am_chat_live
  username: root
  password: root
  host: localhost
