# DB Config file

development:
  adapter: 
  database: am_chat_dev
  username: 
  password: 
  host: localhost

test:
  adapter: cequel
  database: am_chat_test
  username: root
  password: 
  host: localhost

production:
  adapter: 
  database: am_chat_live
  username: 
  password: 
  host: localhost
